# Generated by Django 2.0.5 on 2018-05-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Sante', models.BooleanField(default=False)),
                ('Environnement', models.BooleanField(default=False)),
                ('Travail', models.BooleanField(default=False)),
                ('Solidarite', models.BooleanField(default=False)),
            ],
        ),
    ]
