# Generated by Django 2.0.5 on 2018-05-23 20:48

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('date_start', models.DateTimeField(default='2018-05-23 13:00:11.082200')),
                ('date_end', models.DateTimeField(default='2018-05-23 13:00:11.082200')),
                ('description', models.TextField()),
                ('address', models.TextField(default='adresse')),
                ('inscription', models.TextField(default="mode d'inscription")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Sante', models.BooleanField(default=False)),
                ('Environnement', models.BooleanField(default=False)),
                ('Travail', models.BooleanField(default=False)),
                ('Solidarite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'verbose_name_plural': 'thematiques',
            },
        ),
    ]
