# Generated by Django 2.0.4 on 2018-05-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='Environnement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='Sante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='Solidarite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='Travail',
            field=models.BooleanField(default=False),
        ),
    ]
