# Generated by Django 2.0.4 on 2018-04-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(),
        ),
    ]
