# Generated by Django 2.0.4 on 2018-05-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
    ]
