# Generated by Django 2.0.5 on 2018-05-23 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='Environnement',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='Sante',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='Solidarite',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='Travail',
        ),
        migrations.AddField(
            model_name='entry',
            name='Theme',
            field=models.BooleanField(default=False, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 23, 14, 44, 528583)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='inscription',
            field=models.TextField(default=''),
        ),
    ]
