# Generated by Django 2.0.5 on 2018-05-23 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20180523_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AlterField(
            model_name='entry',
            name='Theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Theme'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 23, 37, 10, 348585)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 23, 37, 10, 348555)),
        ),
    ]
