# Generated by Django 2.0.4 on 2018-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20180508_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('Atelier', 'atelier'), ('Cocktail', 'cocktail'), ('Conference', 'conference'), ('E', 'evenement'), ('Meetup', 'meetup'), ('Projection', 'projection'), ('Reunion', 'reunion')], max_length=2),
        ),
    ]
