# Generated by Django 2.0.5 on 2018-05-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20180523_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('o', 'Offline')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 12, 4, 219467)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 12, 4, 219438)),
        ),
    ]
